### ISSUE TITLE
exporter errors: undefined var

### ISSUE THREAD

**Issue by agileshaw** [canonical/cloudstats#10]
Snap errors with:

Oct  1 15:09:01 juju-7df8cc-21-lxd-7 cloudstats.cloudstats-exporter[47619]: Traceback (most recent call last):
Oct  1 15:09:01 juju-7df8cc-21-lxd-7 cloudstats.cloudstats-exporter[47619]:   File "/snap/cloudstats/x3/bin/cloudstats-exporter", line 33, in <module>
Oct  1 15:09:01 juju-7df8cc-21-lxd-7 cloudstats.cloudstats-exporter[47619]:     sys.exit(load_entry_point('cloudstats==0.1', 'console_scripts', 'cloudstats-exporter')())
Oct  1 15:09:01 juju-7df8cc-21-lxd-7 cloudstats.cloudstats-exporter[47619]:   File "/snap/cloudstats/x3/lib/python3.6/site-packages/cloudstats/exporter.py", line 57, in main
Oct  1 15:09:01 juju-7df8cc-21-lxd-7 cloudstats.cloudstats-exporter[47619]:     time.sleep(self.config["exporter"]["collect_interval"].get(int) * 60)

Indeed, this looks like a copy-paste error in exporter.py, no self in this ctxt:

def main():
    """Provide the daemon entry point."""
    daemon = StatsExporterDaemon(sys.argv[1:])
    daemon.start_http_server()

    while True:
        daemon.run()
        time.sleep(self.config["exporter"]["collect_interval"].get(int) * 60)

**Comment by agileshaw** [comment]
(by [peter-sabaini](https://launchpad.net/~peter-sabaini))
Fixed in bc99f3ccaea4d89b7c419446ca9a2ae96c561c97
