### ISSUE TITLE
Cloudstats fails to collect statistics from Openstack Ocata

### ISSUE THREAD

**Issue by agileshaw** [canonical/cloudstats#5]
snap.cloudstats.cloudstats.service is failing and it is reporting the following exception:

Jun 19 15:13:58 juju-a0c375-3-lxd-1 systemd[1]: Started Service for snap application cloudstats.cloudstats.
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: Traceback (most recent call last):
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: File "/snap/cloudstats/x1/bin/cloudstats", line 11, in <module>
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: load_entry_point('cloudstats==0.1', 'console_scripts', 'cloudstats')()
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/daemon.py", line 92, in main
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: daemon.run()
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/daemon.py", line 82, in run
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: data.update(self.collect_openstack_data())
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/daemon.py", line 67, in collect_openstack_data
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: stats = self.openstack.get_all_stats()
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/opensdk.py", line 202, in get_all_stats
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: stats.update(self._get_hypervisor_stats())
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/opensdk.py", line 479, in _get_hypervisor_stats
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: hypervisor.cpu_info["topology"]["cores"]
Jun 19 15:13:59 juju-a0c375-3-lxd-1 cloudstats.cloudstats[6223]: TypeError: string indices must be integers

and 

Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]: Traceback (most recent call last):
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:   File "/snap/cloudstats/x1/bin/cloudstats", line 33, in <module>
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:     sys.exit(load_entry_point('cloudstats==0.1', 'console_scripts', 'cloudstats')())
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:   File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/daemon.py", line 92, in main
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:     daemon.run()
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:   File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/daemon.py", line 82, in run
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:     data.update(self.collect_openstack_data())
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:   File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/daemon.py", line 67, in collect_openstack_data
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:     stats = self.openstack.get_all_stats()
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:   File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/opensdk.py", line 208, in get_all_stats
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:     stats.update(self._get_network_stats())
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:   File "/snap/cloudstats/x1/lib/python3.6/site-packages/cloudstats/opensdk.py", line 413, in _get_server_stats
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]:     for server in self._servers:
Jul 15 09:30:10 juju-a0c375-3-lxd-1 cloudstats.cloudstats[299291]: KeyError: 'vcpus'
Jul 15 09:30:10 juju-a0c375-3-lxd-1 systemd[1]: snap.cloudstats.cloudstats.service: Main process exited, code=exited, status=1/FAILURE

**Comment by agileshaw** [comment]
(by [aieri](https://launchpad.net/~aieri))
released in 0.0.8
